### ISSUE TITLE
"da pkg" functionality with packages in multiple paths

### ISSUE THREAD

**Issue by bkabrda** [devassistant/devassistant#316]
I've noticed some behaviour that doesn't seem to be correct when packages are installed in mutliple directories that DA loads assistants from. E.g. when `python` DAP is installed in both `/usr/local/share/devassistant` and `~/.devassistant`. Taking `pkg` subcommands one by one:

- [x] `info` is fine
- [x] `install`
  - by default, if user wants to install `python` DAP and it's already in a different load paths (`DATA_DIRECTORIES` from `devassistant.settings`), the requirement should be deemed "satisfied", hence nothing should be done (except of a log message saying that the package is already installed and where with instructions on how to work with package in that path - e.g. "use sudo since package is in `/usr/local/share/devassistant` or use distro-specific means if package is in `/usr/share/devassistant`)
  - by default, if user wants to install `python` DAP (and it's not installed in any load path) and some it's dependencies are satisfied by a package in a different load path, this requirement should be deemed satisfied
  - by default, DAPs should be installed into `DEVASSISTANT_HOME` (from `devassistant.settings`)
  - if a requirement is deemed satisfied, user should be able to "force install" the packages, I'd suggest using `--ignore-installed` (this switch would ignore all installed packages and dependencies in all load paths, hence it would also work as "reinstall")
- [x] `lint` is fine
- [x] `list`
  - listed packages should have format (`packagename (version:loadpath version:loadpath)`) - the version that wins (e.g. the one from the first load path) should be in bold (as should packagename)
  - there should be --quiet switch that would print just package names, one each line, without any bold text (the way it is right now)
- [x] `remove`/`uninstall`
  - [x] should remove only from `DEVASSISTANT_HOME`;
    - [x] if a package to be uninstalled is not in `DEVASSISTANT_HOME`, instructions should be printed about how to handle DAPs in that path (see the `install` section above)
  - [x] there should be an `--all-paths` switch, that would make DA attempt to uninstall DAPs from all paths it's installed in
    - [x] ignoring the distro path `/usr/share/devassistant`
- [x] `search` is fine
- [x] `update`
  - should update only in `DEVASSISTANT_HOME`; if a package to be updated is not in `DEVASSISTANT_HOME`, <del>instructions should be printed about how to handle DAPs in that path (see the `install` section above)</del> new version should be installed to home
  - there should be an `--all-paths` switch, that would make DA attempt to update DAPs in all paths it's installed in (ignoring the distro path `/usr/share/devassistant`)

I hope this makes sense. @tradej @hroncok I'd appreciate comments before we actually start implementing this.

**Comment by bkabrda** [comment]
> Well. By default I can see three locations intended:
> 
>     ~/.devassistant
>     /usr/local/share/devassistant
>     /usr/share/devassistant
> 
> And the switch --all-paths seems useless, as:
> 
>     /usr/share/devassistant should be always ignored/preserved
>     regular user cannot do anything about /usr/local/share/devassistant
>     root should not alter users' ~/.devassistant folders - it is not fair, etc.

It *is* useless *assuming* there are no additional paths specified by environment `DEVASSISTANT_PATH`. With this, user can specify bazillion other paths that have the same DAP installed and we should provide a way to easily uninstall this DAP from all of them, IMO.

**Comment by hroncok** [comment]
Ok, got it. Still need some clarification anyway.

I've read the code in settings.py and I understand how the environment variables for this are working. How exactly should `/usr/share/devassistant` special case be handled?

 1. When this path is present in DEVASSISTANT_PATH environment variable, should it be protected anyway?
 2. When DEVASSISTANT_NO_DEFAULT_PATH is used and this path is in DEVASSISTANT_PATH, should it be protected anyway?
 3. Should there be a way to disable this protection for distribution package maintainers (e.g. when running the commands form .spec file)? If so, how exactly - by command line switch or other environment variable?
 4. Should there be a way to change the path that's protected to some other path by other environment variable (e.g. DEVASSISTANT_DISTRO_HOME)?
 5. If 4., should it be possible to specify more paths to be protected?

**Comment by bkabrda** [comment]
Good questions. My thoughts:

1. When `/usr/share/devassistant` is explicitly added to DEVASSISTANT_PATH, I think it shouldn't be protected. We should just protect it by default.
2. Same as 1.
3. I'm not sure why package maintainers would need to do this exactly. What am I missing?
4. No, this shouldn't be possible at runtime. Distro packagers might however change it by patching `settings.py` when building DA.
5. Since 4. is a no, 5. is also a no (even if 4. was yes, I'd still wouldn't want to make this a general mechanism, it would introduce another level of complexity, IMO).

**Comment by hroncok** [comment]
ad 3. I.e. when we want to run `pkg install` from spec. But in that case we would specify it as DEVASSISTANT_HOME anyway, so never mind.

**Comment by hroncok** [comment]
Other possible issue. Package **b** requires package **a**. Package **a** is installed in `DEVASSISTANT_HOME`, package **b** is installed in `/usr/share/devassistant` (see below about how this crazy situation might happen). User runs the following command:

    da pkg uninstall a

Now devassistant checks that **a** is in `DEVASSISTANT_HOME`, hence being uninstallable. Uninstalls it and want to uninstall **b** as well to not keep a dependency unsatisfied. However, this is not possible, because (1) the user has no right to do it and (2) the `uninstall` comands without a special switch should not do it anyway. Universe collapses, computer explodes, everything is doomed.

How to approach this problem:

 * consider this an impossible state and don't worry, be happy
 * precheck the whole transaction and raise an error before anything happen (might be tricky and very complex if we have some cross dependencies or other forms of dap hell)
 * other way I didn't realized?

Now how the hell this even happens? I have some ideas, non of those is very likely to happen unless somebody does it on purpose. Here is one of them:

 1. as root, install **a** to some crazy directory defined by environment variable(s)
 2. as root, install **b** to standard directory `/usr/share/devassistant`
 3. as user install **a** to standard directory `~/.devassistant`
 
Also, now when I defined this **how-to break devassistant** I realize that unsatisfied dependencies problem might occur just by fiddling with those environment variables while installing stuff.

    DEVASSISTANT_HOME=/tmp/dahome da pkg install common_args
    DEVASSISTANT_PATH=/tmp/dahome da pkg install basically_anything
    da ... basically_anything # undefined mess?

Therefore I think that installing stuff to directories other than default once (for any other purposes than test suite - and we can flexmock this, I guess) might not be a good idea. Do you consider any possible reasonable reason?

I still think it is useful to run assistants from other than default locations, i.e. when you develop them and want to try them out directly from the project dir. But installing/uninstalling/updating stuff in those is a potential disaster.

**Comment by bkabrda** [comment]
I think that if user redefines DEVASSISTANT_HOME, he should know what he's doing. I don't think we can prevent people from shooting themselves in foot. It's just something that normal users shouldn't do.
Having said that, I do think it'd be nice if DA checked that he has correct privileges to manipulate packages that were specified to be uninstalled/updated/whatever. I think pip does that, too.

So let's document that using DEVASSISTANT_HOME/DEVASSISTANT_PATH can be dangerous and may break dependencies if used inappropriately.
