### ISSUE TITLE
No working package manager for "rpm" in: type, type

### ISSUE THREAD

**Issue by aytrack** [devassistant/devassistant#331]
Hello,when I use GUI to create a flask project,i got the error:
No working package manager for "rpm" in: type, type
the version is :DevAssistant 0.10.1
I am a novice , how to solve this problem

**Comment by bkabrda** [comment]
A possible cause:
- you installed DevAssistant using Python 3
- when trying to install Python dependencies, DevAssistant tried to import dnf and hawkey (since yum is not importable on Python 3)
- you don't have hawkey and/or dnf bindings for python3 installed
- neither yum nor dnf package managers were considered working, so DA failed to install deps

Another possible explanation is that you used virtualenv to install DA.

Is any of these assumptions correct? I'll shortly submit a patch that fixes the confusing message with `type: type` and logs some useful info on why certain package managers are unusable (will be visible when DevAssistant is run with --debug in terminal or you click "Debug logs" in GUI).

**Comment by aytrack** [comment]
Here is the result :
> [root@localhost ~]# rpm -q python3-hawkey
> python3-hawkey-0.5.2-1.fc21.x86_64
> [root@localhost ~]# rpm -q python3-dnf
> python3-dnf-0.6.3-2.fc21.noarch

**Comment by bkabrda** [comment]
Ok, now that you have these packages, could you please try retesting with the latest master on Python 3? Everything should work for you now (or the problem was somewhere else...)

**Comment by aytrack** [comment]
I retest Python 3 and it's works !!

**Comment by bkabrda** [comment]
Great, thanks for letting us know. I'll let this issue open until I add some notes about installation for users into our documentation and then I'll close it.

**Comment by tradej** [comment]
Documentation added in a52c4f2c259756418e12ca81ccc254295388bf3e, closing.
