### ISSUE TITLE
fuzzy icons on HiDPI display

### ISSUE THREAD

**Issue by andreasn** [devassistant/devassistant#333]
Running on a 13" screen with 3200x1800 resolution.
![screenshot from 2015-01-09 17 13 39](https://cloud.githubusercontent.com/assets/209895/5682809/15af8c62-9823-11e4-9958-472b160d82b7.png)

**Comment by bkabrda** [comment]
Thanks for the report!
I'm not sure where the problem lies exactly, I see two possible reasons:
1) The mechanics behind rendering icons is somehow wrong, meaning that there is a problem in DA code or GTK. This we can work with.
2) The icon definitions are just not fit to display right on such big resolution. In that case there's almost nothing DevAssistant core can do about this. The path we chose to take is to make individual assistants independent of DA core and make them available on DAPI [1] (this is as of version 0.10.0). Hence we have no control (in general) about what icons people use for their assistants. We still control most of the basic packages on DAPI, so we can *probably* make them more detailed, but I think it won't get to our priority list right now.

We'll try to investigate (any help is welcome :)). @tradej can you have a look at this, please?

[1] https://dapi.devassistant.org/

**Comment by hroncok** [comment]
Note about 2) all of those are vector icons in svgs, so I guess 1) is more probable.

**Comment by tradej** [comment]
I'll have a Chromebook Pixel at my disposal shortly, I'll look into this.
