### ISSUE TITLE
Travis tests for 2.6 are broken

### ISSUE THREAD

**Issue by hroncok** [devassistant/devassistant#381]
We got a lot of

    /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.

in the stderr of our integration tests scenarios and our tests are failing. We should be able to suppress the message somehow using `python -W ignore::DeprecationWarning` if an argument is passed to py.test and pass that argument from Travis on Python 2.6 only? Not to kill other possible DeprecationWarnings.

**Comment by hroncok** [comment]
Or we could hardcode the command line switch here https://github.com/devassistant/devassistant/blob/master/test/integration/misc.py#L42

    if (sys.version_info.major, sys.version_info.minor) == (2, 6):
        cmd.insert(1, '-W')
        cmd.insert(2, 'ignore::DeprecationWarning')

This is a bit ugly, but involves less fiddling with py.test and .travis.yaml

@tradej what do you think?

**Comment by tradej** [comment]
I assume that due to the nature of the warnings, they will pop up for everyone who tries to run the DA tests under Python 2.6. That means that these people also need to run the tests with the switch, and because it's not really DA's fault that they run Python 2.6, it's fair to hardcode ignoring these warnings. Since the DeprecationWarnings aren't skipped with newer Python versions, I say go with the latter solution.,
