### ISSUE TITLE
Unclear prompt for GitHub password

### ISSUE THREAD

**Issue by ncoghlan** [devassistant/devassistant#386]
When using DA to automatically create a new project in GitHub, the dialog the pops up provides very little indication that it is requesting GitHub login credentials.

**Comment by tradej** [comment]
Can you please provide a screenshot? Thank you.

**Comment by ncoghlan** [comment]
Hmm, it didn't prompt me this time. Would DevAssistant have saved the original credentials or an access token somewhere?

**Comment by hroncok** [comment]
Yes, to the global git config.

    github.token.hroncok=xxxxxx
    github.user.hroncok=hroncok

**Comment by ncoghlan** [comment]
Removing the previously saved token so it prompted me again, I see in the taskbar this time that the password entry windows does have an appropriate title. However (at least under KDE), it's getting resized to match the size of the password field, so there's no room for the title in the title bar of the window itself:

<img width="438" alt="devassistant_github_password_prompt" src="https://cloud.githubusercontent.com/assets/1026649/9599624/a867f7f6-50d8-11e5-866b-afb854e31031.png">

**Comment by tradej** [comment]
This is related to how the dialogue is displayed in KDE—it works in GNOME. Since the GTK-based GUI is to be dropped in the coming months in favour of a web-based one, I'll close this bug as wontfix. We currently don't have the manpower to deal with this issue, I'm afraid. Thanks for reporting it anyway.
